# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  app_id: "id-here"
  api_key: "api-key-here"
  secret_key: "secret-key-here"
  canvas_page_name:
  callback_url: "http://localhost:3000"
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000

# Same as development
staging:
  app_id: "app-id-here"
  api_key: "api-key-here"
  secret_key: "secret-key-here"
  canvas_page_name:
  callback_url: "http://staging.socialnews.com"
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000

production:
  app_id: "app-id-here"
  api_key: "api-key-here"
  secret_key: "secret-key-here"
  canvas_page_name: 
  callback_url: "http//socialnews.com"
  set_asset_host_to_callback_url: false   
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000

test:
  app_id: "73616968934"
  api_key: "dd320777329ceed5337901b1a05ef177"
  secret_key: "11a0ca80a572199f3c6a90d984a38e38"
  canvas_page_name: 
  callback_url: "http://localhost:3000"
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
